name: CD

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}  # permet de relancer manuellement

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/score-octroi

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker Hub secrets
        run: |
          if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
            echo "Missing Docker Hub credentials. Add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets."
            exit 1
          fi
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        working-directory: web
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Publish metrics as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: service/artifacts/model_v1.0.0/metrics.json