name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Validate performance thresholds
        run: |
          python - << 'PY'
          import json, pathlib
          p = pathlib.Path("service/artifacts/model_v1.0.0/metrics.json")
          m = json.loads(p.read_text())
          assert m["auc"] >= 0.70, f"AUC too low: {m['auc']}"
          assert m["psi"] <= 0.2, f"PSI too high: {m['psi']}"
          print("Metrics OK:", m)
          PY

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build frontend
        working-directory: web
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Build Docker image (no push)
        run: docker build -t ${{ github.repository }}:ci .